server.port=8080
# ? Dynamic (Works on both Local & Render)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/marketplace_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings to automatically build/update tables based on your Java models
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

debug=true

